//
//  TouchBarAccountButtons.swift
//  Balance
//
//  Created by Christian Baroni on 12/10/16.
//  Copyright © 2016 Balance. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


public struct TouchBarAccountButtons  {

}
